name = "qitops-learn"
compatibility_date = "2024-03-29"
pages_build_output_dir = "./build/client"

[[d1_databases]]
binding = "DB"
database_name = "qitops-learn-db"
database_id = "55d34980-fa85-4cc2-8140-fde070bab2f0"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "qitops-assets"

[[kv_namespaces]]
binding = "KV_NAMESPACE"
id = "bb9c14e33238477aa5485ecc9439dcef"